# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

# Facebook
pod 'FBSDKLoginKit'

# Google
pod 'GoogleSignIn'

# Messages
pod 'MessageKit'

# Great activity
pod 'JGProgressHUD'

# Database (simple cash)
pod 'RealmSwift'

# Web loading image URL
pod 'SDWebImage'

end
